name: sccoda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.10.8
  - readline=8.2
  - setuptools=67.7.2
  - tk=8.6.12
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
    - absl-py==1.4.0
    - adjusttext==0.7.3
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anndata==0.9.1
    - arrow==1.2.3
    - arviz==0.15.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - cached-property==1.5.2
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - chex==0.1.7
    - click==8.1.3
    - cmake==3.26.3
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - custom-inherit==2.4.1
    - cycler==0.11.0
    - decoupler==1.3.4
    - dm-tree==0.1.8
    - docrep==0.3.2
    - et-xmlfile==1.1.0
    - ete3==3.1.3
    - etils==1.2.0
    - filelock==3.12.0
    - flax==0.6.9
    - fonttools==4.39.3
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - future==0.18.3
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.54.0
    - h5netcdf==1.1.0
    - h5py==3.8.0
    - idna==3.4
    - igraph==0.10.4
    - importlib-resources==5.12.0
    - ipywidgets==8.0.6
    - jax==0.4.8
    - jaxlib==0.4.7
    - jaxopt==0.6
    - jinja2==3.1.2
    - joblib==1.2.0
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - leidenalg==0.9.1
    - lit==16.0.2
    - llvmlite==0.39.1
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mizani==0.9.0
    - ml-collections==0.1.1
    - ml-dtypes==0.1.0
    - mpmath==1.3.0
    - msgpack==1.0.5
    - mudata==0.2.2
    - multidict==6.0.4
    - multipledispatch==0.6.0
    - muon==0.1.3
    - natsort==8.3.1
    - networkx==3.1
    - numba==0.56.4
    - numpy==1.23.5
    - numpyro==0.11.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - optax==0.1.5
    - orbax-checkpoint==0.2.1
    - ott-jax==0.4.0
    - packaging==23.1
    - pandas==2.0.0
    - patsy==0.5.3
    - pertpy==0.4.0
    - pexpect==4.8.0
    - pillow==9.5.0
    - plotnine==0.10.1
    - ply==3.11
    - protobuf==3.20.1
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pynndescent==0.5.10
    - pyomo==6.5.0
    - pyparsing==3.0.9
    - pypi-latest==0.1.2
    - pypng==0.20220715.0
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.12.1
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pytorch-lightning==1.7.7
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - questionary==1.10.0
    - reportlab==3.6.13
    - requests==2.30.0
    - requests-oauthlib==1.3.1
    - rich==13.3.5
    - rpy2==3.5.11
    - rsa==4.9
    - scanpy==1.9.3
    - scikit-learn==1.2.2
    - scikit-misc==0.1.4
    - scipy==1.10.1
    - scvi-tools==0.19.0
    - seaborn==0.11.2
    - session-info==1.0.0
    - six==1.16.0
    - sparsecca==0.3.0
    - statannotations==0.5.0
    - statsmodels==0.14.0rc0
    - stdlib-list==0.8.0
    - switchlang==0.1.0
    - sympy==1.11.1
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.0
    - tensorstore==0.1.36
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - torch==2.0.0
    - torchmetrics==0.11.4
    - toyplot==1.0.3
    - toytree==2.0.1
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - tzlocal==4.3
    - umap-learn==0.5.3
    - urllib3==2.0.2
    - werkzeug==2.3.3
    - widgetsnbextension==4.0.7
    - xarray==2023.4.2
    - xarray-einstats==0.5.1
    - yarl==1.9.2

